[package]
name = "executor-trait"
version = "0.0.0"
authors = ["Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
edition = "2018"
description = "reserved"
license = "MIT"

[dependencies]
async-trait = "*"
